configurable linux kernel headers location
piraeusdatastore/piraeus-operator pull request #146
Opened 2021-01-07 16:01 UTC by dkhachyan

In OpenShift environment(FCOS) kernel headers are not accessible in /usr/src directory
Additionaly /usr/src this directory is ReadOnly in FCOS.
We have to download kernel headers inside kernel injector container, during entrypoint, or when building
 docker image(in offline configuration), like
https://gitlab.com/nvidia/container-images/driver/-/blob/master/ubuntu16.04/nvidia-driver

2021-01-08 08:23 UTC, WanzenBug commented
Hey! Any particular reason this was closed? At first glance it looks useful.

2021-01-08 11:00 UTC, dkhachyan commented
Ok, then i'll try to fix validation errors... have you any recommendations
after review?

2021-01-08 11:19 UTC, WanzenBug requested changes
Re validation-errors: We use [`pre-commit`](https://pre-commit.com/) to validate each PR. If you install that it will run the necessary validation before you commit.

So I just had to think about the exact use again: We are running on a host without kernel headers, which means they have to be packaged with the image already. But that means the image could already contain the logic to set the header location, right?

2021-01-08 12:00 UTC, dkhachyan commented
When we are running on a host without kernel headers we can use a scenario like this:
- Disable mounting /usr/src
- Query kernel version in entry.sh
- Download kernel headers in entry.sh
- when offline, we can download kernel headers during image build

When /usr/src mount is enabled, it overwrites everything in /usr/src when pod starts
As far as I no, almost all linux distributions installs headers exactly in /usr/src, and we can not change this directory during package install. May be we can move kernel headers into any other dir after package installation and use KDIR environment variable, but this can only be done during image build.

2021-01-08 13:52 UTC, WanzenBug commented
The problem I see is with:

> * Download kernel headers in entry.sh

This is heavily dependent on which distribution you are using. We could make it work for just FCOS, but I'd rather not special-case another distribution.

If we want to make it work for offline environments, it would not work anyways. So how about we instead
Provide instructions on how to build your own image. With that I mean something like:
```
FROM fedora:33 as kernel-src
RUN dnf update && dnf install -y kernel-devel

FROM quay.io/piraeusdatastore/drbd9-centos8:v9.0.27-1
COPY --from=kernel-src /usr/src /opt/kernel-src
ENV KDIR=/opt/kernel-src
```
This image can then replace the default image, and it should use the packaged kernel sources rather than reading from `/usr/src`
I think this would be "good enough"

2021-01-10 11:35 UTC, dkhachyan commented
OK, thanks!

2021-01-10 11:35 UTC, closed without merging

2021-01-12 15:25 UTC, WanzenBug commented
@dkhachyan did you manage to install DRBD on FCOS? During #149 I tried adding a section which describes the above Dockerfile method. During that I noticed:
* There is no matching `kernel-devel` package available for the kernel used by FCOS
* The one `kernel-devel` package that was available does not seem to be compatible with DRBD from my short tests

So I was wondering if you managed to get something running?

2021-01-15 09:48 UTC, dkhachyan commented
@WanzenBug, sorry for the long answer. I use koji, to install kernel headers in FCOS

```
RUN dnf install -y \
        koji  && \
        koji download-build --rpm --arch=x86_64 kernel-devel-${KERNEL_VERSION} && \
        dnf install -y kernel-devel-${KERNEL_VERSION}.rpm && \
        rm -f kernel-devel-${KERNEL_VERSION}.rpm && \
    rm -rf /var/cache/yum/*
```