Updated registry mirror for chinese users
piraeusdatastore/piraeus-operator pull request #423
Opened 2023-03-09 14:24 UTC by wangjiusi

We are automatically syncing all images to `m.daocloud.io` registry (refreshing each day). 

The following script convert all registry addresses to those of daocloud mirror.  

```
cd piraeus-operator/charts/piraeus

cat values.yaml \
| sed 's/docker.io/docker.m.daocloud.io/' \
| sed 's/quay.io/quay.m.daocloud.io/' \
| sed 's/registry.k8s.io/k8s-gcr.m.daocloud.io/' \
| sed 's/k8s.gcr.io/k8s-gcr.m.daocloud.io/' \
| sed 's/gcr.io/gcr.m.daocloud.io/' \
| sed 's/ghcr.io/gcr.m.daocloud.io/' \
| sed 's/bionic/centos7/' \
> values.cn.yaml
```

PS: We also default the drbd loader image to `centos7` as it is more popular than `ubuntu` in China.

2023-03-09 14:25 UTC, alexzhc commented
@rck Hi, Roland. We are using auto script to syncing images to `m.daocloud.io` registries. The new `values.cn.yaml` is test working.

2023-03-09 14:27 UTC, alexzhc commented
@rck, we are now using automated script to sync all related images to `m.daocloud.io` registry. The new `values.cn.yaml`  is tested working.

2023-03-09 14:50 UTC, rck approved these changes
LGTM

2023-03-09 15:04 UTC, rck commented
I see, we also need that changes in that test I assume otherwise the checks' `sed` fails. Hm, I'm sure @WanzenBug knows the details, so I would like to wait till he fixed that part. AFAIK he will be back on Mon.

2023-03-13 07:39 UTC, WanzenBug commented
You'll want to update the [`Makefile`](https://github.com/piraeusdatastore/piraeus-operator/blob/master/Makefile#L38-L45), otherwise the changes will be overwritten on every update.

@wangjiusi Does the mirror apply to _all_ images for quay.io/piraeusdatastore or just the ones referenced in values.yaml?

2023-03-13 08:04 UTC, alexzhc commented
@WanzenBug the complete mirror list is here: <https://github.com/DaoCloud/public-image-mirror/blob/main/mirror.txt>. Can be updated to sync more images by PRs.

2023-03-13 08:11 UTC, wangjiusi commented
> You'll want to update the [`Makefile`](https://github.com/piraeusdatastore/piraeus-operator/blob/master/Makefile#L38-L45), otherwise the changes will be overwritten on every update.
> 
> @wangjiusi Does the mirror apply to _all_ images for quay.io/piraeusdatastore or just the ones referenced in values.yaml?

@WanzenBug just ones in values.yaml, including quay.io, registry.k8s.io, docker.io

2023-03-13 15:04 UTC, WanzenBug requested changes

2023-03-13 15:04 UTC, WanzenBug commented on Makefile
> +      > ./charts/piraeus/values.cn.yaml
Almost there. Just a little trailing whitespace that our checks dont like here:

```suggestion
      > ./charts/piraeus/values.cn.yaml
```

2023-03-13 15:15 UTC, WanzenBug requested changes
There is one extra space, still :slightly_smiling_face:

2023-03-13 16:14 UTC, WanzenBug approved these changes

2023-03-13 16:15 UTC, merged